#**Trabalhando com Planilhas do Excel**

In [2]:
#Importando a biblioteca
import pandas as pd

In [3]:
#Leitura dos arquivos
df1 = pd.read_excel("drive/MyDrive/dataset/Aracaju.xlsx")
df2 = pd.read_excel("drive/MyDrive/dataset/Fortaleza.xlsx")
df3 = pd.read_excel("drive/MyDrive/dataset/Natal.xlsx")
df4 = pd.read_excel("drive/MyDrive/dataset/Recife.xlsx")
df5 = pd.read_excel("drive/MyDrive/dataset/Salvador.xlsx")

In [4]:
df5.head()

     Cidade       Data  Vendas  LojaID  Qtde
0  Salvador 2018-01-01   31.06    1037     3
1  Salvador 2018-01-01   19.02    1034     3
2  Salvador 2019-02-10  173.59    1035     3
3  Salvador 2019-02-10  176.34    1037     3
4  Salvador 2019-02-14   19.47    1037     3

In [5]:
#juntando todos os arquivos
df = pd.concat([df1,df2,df3,df4,df5])

In [6]:
#Exibindo as 5 primeiras linhas
df.head()

    Cidade       Data  Vendas  LojaID  Qtde
0  Aracaju 2018-01-01  142.00    1520     1
1  Aracaju 2018-01-01   14.21    1522     6
2  Aracaju 2018-01-01   71.55    1520     1
3  Aracaju 2018-01-01    3.01    1521     7
4  Aracaju 2018-01-01   24.51    1522     8

In [7]:
#Exibindo as 5 Ãºltimas linhas
df.tail()

       Cidade       Data  Vendas  LojaID  Qtde
235  Salvador 2019-01-03   41.84    1034     1
236  Salvador 2019-01-03  126.29    1035     3
237  Salvador 2019-01-03   38.06    1036     3
238  Salvador 2019-01-03  139.64    1035     1
239  Salvador 2019-01-03  161.41    1037     3

In [8]:
df.sample(5)

        Cidade       Data  Vendas  LojaID  Qtde
117      Natal 2019-01-02   39.41    1034     1
81       Natal 2019-04-02  564.00     854     2
98   Fortaleza 2019-01-01   15.00    1005     2
70       Natal 2019-02-14  743.00     854     4
49     Aracaju 2018-01-01   53.74    1522     3

In [9]:
#Verificando o tipo de dado de cada coluna
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID             int64
Qtde               int64
dtype: object

In [10]:
#Alterando o tipo de dado da coluna LojaID
df["LojaID"] = df["LojaID"].astype("object")

In [11]:
df.dtypes

Cidade            object
Data      datetime64[ns]
Vendas           float64
LojaID            object
Qtde               int64
dtype: object

In [12]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde
0  Aracaju 2018-01-01  142.00   1520     1
1  Aracaju 2018-01-01   14.21   1522     6
2  Aracaju 2018-01-01   71.55   1520     1
3  Aracaju 2018-01-01    3.01   1521     7
4  Aracaju 2018-01-01   24.51   1522     8

**Tratando valores faltantes**

In [13]:
#Consultando linhas com valores faltantes
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [14]:
#Substituindo os valores nulos pela mÃ©dia
df["Vendas"].fillna(df["Vendas"].mean(), inplace=True)

In [15]:
df["Vendas"].mean()

122.61180089485438

In [16]:
df.isnull().sum()

Cidade    0
Data      0
Vendas    0
LojaID    0
Qtde      0
dtype: int64

In [17]:
df.sample(15)

        Cidade       Data  Vendas LojaID  Qtde
78    Salvador 2019-01-01  111.20   1036     3
106     Recife 2019-01-01   30.46    982     3
60       Natal 2018-05-02  534.00    852     3
31       Natal 2018-04-03  401.00    854     4
1     Salvador 2018-01-01   19.02   1034     3
141      Natal 2019-01-02    9.08   1036     1
92       Natal 2019-01-02    4.57   1035     1
172   Salvador 2019-01-02    6.70   1035     1
211      Natal 2019-01-02  141.05   1035     3
59       Natal 2018-01-15  369.00    853     2
148   Salvador 2019-01-02   40.59   1037     3
12       Natal 2019-02-02  709.00    853     3
117     Recife 2019-03-02   15.42    983     8
134  Fortaleza 2019-03-02  195.18    980     5
136   Salvador 2019-03-02   13.81   1036     1

In [18]:
#Substituindo os valores nulos por zero
df["Vendas"].fillna(0, inplace=True)

In [19]:
#Apagando as linhas com valores nulos
df.dropna(inplace=True)

In [20]:
#Apagando as linhas com valores nulos com base apenas em 1 coluna
df.dropna(subset=["Vendas"], inplace=True)

In [21]:
#Removendo linhas que estejam com valores faltantes em todas as colunas
df.dropna(how="all", inplace=True)

**Criando colunas novas**

In [22]:
#Criando a coluna de receita
df["Receita"] = df["Vendas"].mul(df["Qtde"])

In [23]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita
0  Aracaju 2018-01-01  142.00   1520     1   142.00
1  Aracaju 2018-01-01   14.21   1522     6    85.26
2  Aracaju 2018-01-01   71.55   1520     1    71.55
3  Aracaju 2018-01-01    3.01   1521     7    21.07
4  Aracaju 2018-01-01   24.51   1522     8   196.08

In [24]:
df["Receita/Vendas"] = df["Receita"] / df["Vendas"]

In [25]:
df.head()

    Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
0  Aracaju 2018-01-01  142.00   1520     1   142.00             1.0
1  Aracaju 2018-01-01   14.21   1522     6    85.26             6.0
2  Aracaju 2018-01-01   71.55   1520     1    71.55             1.0
3  Aracaju 2018-01-01    3.01   1521     7    21.07             7.0
4  Aracaju 2018-01-01   24.51   1522     8   196.08             8.0

In [26]:
#Retornando a maior receita
df["Receita"].max()

3544.0

In [27]:
#Retornando a menor receita
df["Receita"].min()

3.34

In [28]:
#nlargest
df.nlargest(3, "Receita")

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0

In [29]:
#nsamllest
df.nsmallest(3, "Receita")

      Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
118  Aracaju 2018-01-01    3.34   1522     1     3.34             1.0
65    Recife 2019-01-01    4.01    981     1     4.01             1.0
92     Natal 2019-01-02    4.57   1035     1     4.57             1.0

In [30]:
#Agrupamento por cidade
df.groupby("Cidade")["Receita"].sum()

Cidade
Aracaju       48748.25
Fortaleza     37913.97
Natal        167227.52
Recife        51936.51
Salvador      40596.73
Name: Receita, dtype: float64

In [31]:
#Ordenando o conjunto de dados
df.sort_values("Receita", ascending=False).head(10)

   Cidade       Data  Vendas LojaID  Qtde  Receita  Receita/Vendas
7   Natal 2019-03-18   886.0    853     4   3544.0             4.0
55  Natal 2019-01-08   859.0    854     4   3436.0             4.0
51  Natal 2018-01-21   859.0    852     4   3436.0             4.0
30  Natal 2018-10-02   856.0    853     4   3424.0             4.0
41  Natal 2018-05-20   835.0    852     4   3340.0             4.0
38  Natal 2018-02-25   828.0    852     4   3312.0             4.0
10  Natal 2018-10-27   828.0    852     4   3312.0             4.0
69  Natal 2019-03-24   817.0    852     4   3268.0             4.0
62  Natal 2018-02-10   793.0    854     4   3172.0             4.0
52  Natal 2018-04-27   778.0    854     4   3112.0             4.0